#!/usr/bin/env node

var fs = require('fs')
fs.writeFileSync('capsule.log', 'node parser was called but nothing happened', 'utf8')

var url = require('url')

// parse URL, split up query params
var uri = process.argv[2]
var parsedURI = url.parse(uri)
payloadArray = parsedURI.query.split(/[\=\&]/)

// convert to key-val dict
var payload = {}
var keysToParse = ['body', 'title', 'src', 'comment', 'channel', 'mentions']
keysToParse.forEach(function(key) {
  const keyPos = payloadArray.indexOf(key)
  if (keyPos !== -1) {
    payload[key] = payloadArray[keyPos + 1]
  }
})

// decode payload from base64
payload.body = unescape(new Buffer(payload.body, 'base64').toString())
if (typeof payload.comment === 'string') {
  payload.body = payload.body.concat('\n<hr /><br />').concat(unescape(payload.comment))
}
payload.title = unescape(payload.title)
payload.channel = unescape(payload.channel)

// ssbify the thing, finally
var ssbifyString = require('ssbify-string')
var ssbClient = require('ssb-client')

ssbClient(function (err, sbot) {
  if (err) fs.writeFileSync('capsule.log', err, 'utf8')
  
  
  ssbifyString(
    sbot, payload.body,
    { ignoreBrokenLinks: true, url: payload.src, title: payload.title },
    function(err, res) {
      if (err) fs.writeFileSync('capsule.log', err, 'utf8')
      else fs.writeFileSync('capsule.log', res, 'utf8')


      // TODO preflight check to ensure a gross post is not pushed instead

      // publish a message
      sbot.publish({ type: 'post', text: res, channel: payload.channel || '' }, 
                   function (err, msg) {
                     if (err) fs.writeFileSync('capsule.log', err, 'utf8')
                   })
  
    })
})
